const path = require('path')
const fs = require('fs')

// The AppRun generated by electron-builder calls exec "$BIN" where BIN is the
// app executable. We rename the real Electron binary to <name>.bin and replace
// it with a tiny shell script that adds --no-sandbox. The AppRun never changes.
// This is needed on Ubuntu 23.10+ where the SUID sandbox cannot run in AppImage.
exports.default = async function (context) {
  if (context.electronPlatformName !== 'linux') return

  const appOutDir = context.appOutDir
  const execName = context.packager.executableName || 'medicinestrip-ai'

  const binaryPath    = path.join(appOutDir, execName)
  const binaryBinPath = path.join(appOutDir, `${execName}.bin`)

  if (!fs.existsSync(binaryPath)) {
    console.log('[afterPack] binary not found:', binaryPath)
    return
  }

  fs.renameSync(binaryPath, binaryBinPath)

  const wrapper = [
    '#!/bin/sh',
    `exec "$(dirname "$0")/${execName}.bin" "$@" --no-sandbox`,
  ].join('\n') + '\n'

  fs.writeFileSync(binaryPath, wrapper)
  fs.chmodSync(binaryPath, '0755')

  console.log(`[afterPack] wrapped ${execName} → ${execName}.bin + shell script with --no-sandbox`)
}
